name: changed files workflow tests

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  change-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v42
        id: changed
        with:
          since_last_remote_commit: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
          files: |
            README.md
            tests/**

      - if: steps.changed.outputs.any_modified == 'true'
        run: |
          echo "Files changed"

      - if: success()
        run: |
          echo "OK"
